### ISSUE TITLE
switch the ncp commands

### ISSUE THREAD

**Issue by ThorstenHans** [thinktecture/basta-spring-2018-xplatform-ws#1]
Instead of using

```
ncp build dist/mobile/www && ncp resources/cordova dist/mobile
```

I would do

```
ncp resources/cordova dist/mobile && ncp build dist/mobile/www
```

That change would ensure that compiled SPA copied to the output directory. Ran into an issue earlier the day with non-working `cordova create --link-to` so I ended up with the sample `www` folder of cordova in `resources/cordova`.

By switching the copy commands, you can eliminate the risk for that one.

https://github.com/thinktecture/basta-spring-2018-xplatform-ws/blob/6df731eefd4b8794190b48af099a45a3039e3d87/package.json#L18

**Comment by christianliebel** [comment]
Thanks a lot! We appreciate your feedback.
